image: Visual Studio 2017

# Test against the latest version of this Node.js version
environment:
  nodejs_version: "8.9.1"

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node $env:nodejs_version x86
  - npm install

build_script:
  - npm run publish

test: off